# Generated by Django 3.2 on 2021-06-16 07:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userblog', '0002_blogcomment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BlogComment',
        ),
    ]
