# Generated by Django 3.2 on 2021-05-31 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='uses',
            new_name='user',
        ),
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='user.jfif', upload_to='Profilepics/'),
        ),
    ]
